name: Release publish

on:
  release:
    types: [published]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  compile:
    name: Ping
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get commit SHA
      id: commit_id
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Getbranch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: branch_name

    # If none of these files has changed, we assume that the contents of .m2/repository can be fetched from the cache.
    - name: Ping pong
      run: |
        echo 'Release publish, branch: ${{ steps.branch_name.outputs.branch }}, commit_id: ${{ steps.commit_id.outputs.sha_short }}'

    - name: Update release file
      run: |
        echo '${{steps.commit_id.outputs.sha_short}}' > commit.txt
        
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Change release to ${{ steps.commit_id.outputs.sha_short  }}"
        git tag -f release

    - name: Commit files
      run: |
        env

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        force: 'true'
        tags: 'true'